#debug: true

spring:
  application:
    name: login-demo
  datasource:
    url: jdbc:mysql://mysql:3306/demo_login?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: roki
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
      #    password: # 如果有密码，写在这里；没有就删除这一行
      timeout: 5000


mybatis:
  type-aliases-package: com.example.logindemo.infra.po
  mapper-locations: classpath*:mapper/*.xml

jwt:
  secret: your-256-bit-secret-your-256-bit-secret
  expire: 3600000 # 毫秒：1小时


logging:
  level:
    com.example.logindemo: info  # 你的业务包
    org.mybatis: debug          # MyBatis 本身
    org.mybatis.spring.SqlSessionFactoryBean: debug
    org.apache.ibatis: debug    # ⬅️ 打印 SQL 和参数
